<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiseasesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $diseases = array(
            array("diagnosa"=>"Fever, unspecified","id"=>"1","kode_penyakit"=>"R50.9"),
            array("diagnosa"=>"Typhoid and paratyphoid fevers","id"=>"2","kode_penyakit"=>"A01"),
            array("diagnosa"=>"Essential (primary) hypertension","id"=>"3","kode_penyakit"=>"I10"),
            array("diagnosa"=>"Asthma","id"=>"4","kode_penyakit"=>"J45"),
            array("diagnosa"=>"Acute upper respiratory infection, unspecified","id"=>"5","kode_penyakit"=>"J06.9"),
            array("diagnosa"=>"Nausea and vomiting","id"=>"6","kode_penyakit"=>"R11"),
            array("diagnosa"=>"Diarrhoea and gastroenteritis of presumed infectious origin","id"=>"7","kode_penyakit"=>"A09"),
            array("diagnosa"=>"Erosive (osteo)arthrosis","id"=>"8","kode_penyakit"=>"M15.4"),
            array("diagnosa"=>"Influenza with other respiratory manifestations, virus not identified","id"=>"9","kode_penyakit"=>"J11.1"),
            array("diagnosa"=>"Acute pharyngitis","id"=>"10","kode_penyakit"=>"J02"),
            array("diagnosa"=>"Other benign neoplasm of connective and other soft tissue, unspecified","id"=>"11","kode_penyakit"=>"D21.9"),
            array("diagnosa"=>"Gastritis, unspecified","id"=>"12","kode_penyakit"=>"K29.7"),
            array("diagnosa"=>"Nonorganic insomnia","id"=>"13","kode_penyakit"=>"F51.0"),
            array("diagnosa"=>"Epilepsy","id"=>"14","kode_penyakit"=>"G40"),
            array("diagnosa"=>"Non-insulin-dependent diabetes mellitus","id"=>"15","kode_penyakit"=>"E11"),
            array("diagnosa"=>"Cystitis","id"=>"16","kode_penyakit"=>"N30"),
            array("diagnosa"=>"Ventricular fibrillation and flutter","id"=>"17","kode_penyakit"=>"I49.0"),
            array("diagnosa"=>"Mild vaginal dysplasia","id"=>"18","kode_penyakit"=>"N89.0"),
            array("diagnosa"=>"Respiratory tuberculosis, not confirmed bacteriologically or histologically","id"=>"19","kode_penyakit"=>"A16"),
            array("diagnosa"=>"Acute upper respiratory infections of multiple and unspecified sites","id"=>"20","kode_penyakit"=>"J06"),
            array("diagnosa"=>"Cough","id"=>"21","kode_penyakit"=>"R05"),
            array("diagnosa"=>"Dermatographic urticaria","id"=>"22","kode_penyakit"=>"L50.3"),
            array("diagnosa"=>"Tension-type headache","id"=>"23","kode_penyakit"=>"G44.2"),
            array("diagnosa"=>"Other chronic obstructive pulmonary disease","id"=>"24","kode_penyakit"=>"J44"),
            array("diagnosa"=>"Non-insulin-dependent diabetes mellitus with peripheral circulatory complications","id"=>"25","kode_penyakit"=>"E11.5"),
            array("diagnosa"=>"Benign paroxysmal verti","id"=>"26","kode_penyakit"=>"H81.1"),
            array("diagnosa"=>"Arthritis, unspecified","id"=>"27","kode_penyakit"=>"M13.9"),
            array("diagnosa"=>"Thyrotoxicosis [hyperthyroidism]","id"=>"28","kode_penyakit"=>"E05"),
            array("diagnosa"=>"Q fever","id"=>"29","kode_penyakit"=>"A78"),
            array("diagnosa"=>"Sciatica","id"=>"30","kode_penyakit"=>"M54.3"),
            array("diagnosa"=>"Tuberculosis of lung, confirmed by sputum microscopy with or without culture","id"=>"31","kode_penyakit"=>"A15.0"),
            array("diagnosa"=>"Caries of dentine","id"=>"32","kode_penyakit"=>"K02.1"),
            array("diagnosa"=>"Impacted teeth","id"=>"33","kode_penyakit"=>"K01.1"),
            array("diagnosa"=>"Atopic dermatitis, unspecified","id"=>"34","kode_penyakit"=>"L20.9"),
            array("diagnosa"=>"Neuralgia and neuritis, unspecified, shoulder region","id"=>"35","kode_penyakit"=>"M79.21"),
            array("diagnosa"=>"Injury of unspecified body region","id"=>"36","kode_penyakit"=>"T14"),
            array("diagnosa"=>"Sprain and strain of toe(s)","id"=>"37","kode_penyakit"=>"S93.5"),
            array("diagnosa"=>"Other arthritis","id"=>"38","kode_penyakit"=>"M13"),
            array("diagnosa"=>"Varicella [chickenpox]","id"=>"39","kode_penyakit"=>"B01"),
            array("diagnosa"=>"Disturbances in tooth eruption","id"=>"40","kode_penyakit"=>"K00.6"),
            array("diagnosa"=>"Acute abdomen","id"=>"41","kode_penyakit"=>"R10.0"),
            array("diagnosa"=>"Neuralgia and neuritis, unspecified, multiple sites","id"=>"42","kode_penyakit"=>"M79.20"),
            array("diagnosa"=>"Low back pain","id"=>"43","kode_penyakit"=>"M54.5"),
            array("diagnosa"=>"Neuralgia and neuritis, unspecified","id"=>"44","kode_penyakit"=>"M79.2"),
            array("diagnosa"=>"Headache","id"=>"45","kode_penyakit"=>"R51"),
            array("diagnosa"=>"Neuralgia and neuritis, unspecified, lower leg","id"=>"46","kode_penyakit"=>"M79.26"),
            array("diagnosa"=>"Influenza with other manifestations, virus not identified","id"=>"47","kode_penyakit"=>"J11.8"),
            array("diagnosa"=>"Allergic contact dermatitis","id"=>"48","kode_penyakit"=>"L23"),
            array("diagnosa"=>"Rheumatism, unspecified","id"=>"49","kode_penyakit"=>"M79.0"),
            array("diagnosa"=>"Other seasonal allergic rhinitis","id"=>"50","kode_penyakit"=>"J30.2"),
            array("diagnosa"=>"Disorders of purine and pyrimidine metabolism","id"=>"51","kode_penyakit"=>"E79"),
            array("diagnosa"=>"Generalized anxiety disorder","id"=>"52","kode_penyakit"=>"F41.1"),
            array("diagnosa"=>"Chronic ischaemic heart disease","id"=>"53","kode_penyakit"=>"I25"),
            array("diagnosa"=>"Hyperlipidaemia, unspecified","id"=>"54","kode_penyakit"=>"E78.5"),
            array("diagnosa"=>"Other disorders of white blood cells","id"=>"55","kode_penyakit"=>"D72"),
            array("diagnosa"=>"Fracture of upper end of humerus, closed","id"=>"56","kode_penyakit"=>"S42.20"),
            array("diagnosa"=>"Chronic obstructive pulmonary disease with acute lower respiratory infection","id"=>"57","kode_penyakit"=>"J44.0"),
            array("diagnosa"=>"Acute nasopharyngitis [common cold]","id"=>"58","kode_penyakit"=>"J00"),
            array("diagnosa"=>"Iron deficiency anaemia","id"=>"59","kode_penyakit"=>"D50"),
            array("diagnosa"=>"Conjunctivitis","id"=>"60","kode_penyakit"=>"H10"),
            array("diagnosa"=>"Hyperuricaemia without signs of inflammatory arthritis and tophaceous disease","id"=>"61","kode_penyakit"=>"E79.0"),
            array("diagnosa"=>"Hypertensive heart disease without (congestive) heart failure","id"=>"62","kode_penyakit"=>"I11.9"),
            array("diagnosa"=>"Insulin-dependent diabetes mellitus with ophthalmic complications","id"=>"63","kode_penyakit"=>"E10.3"),
            array("diagnosa"=>"Malignant neoplasm of breast, unspecified","id"=>"64","kode_penyakit"=>"C50.9"),
            array("diagnosa"=>"Other chest pain","id"=>"65","kode_penyakit"=>"R07.3"),
            array("diagnosa"=>"Typhoid fever","id"=>"66","kode_penyakit"=>"A01.0"),
            array("diagnosa"=>"Dermatitis, unspecified","id"=>"67","kode_penyakit"=>"L30.9"),
            array("diagnosa"=>"Pulpitis","id"=>"68","kode_penyakit"=>"K04.0"),
            array("diagnosa"=>"Astigmatism","id"=>"69","kode_penyakit"=>"H52.2"),
            array("diagnosa"=>"Sequelae of stroke, not specified as haemorrhage or infarction","id"=>"70","kode_penyakit"=>"I69.4"),
            array("diagnosa"=>"Senile cataract","id"=>"71","kode_penyakit"=>"H25"),
            array("diagnosa"=>"Chronic kidney disease, stage 5","id"=>"72","kode_penyakit"=>"N18.5"),
            array("diagnosa"=>"Chalazion","id"=>"73","kode_penyakit"=>"H00.1"),
            array("diagnosa"=>"Diseases of pulp and periapical tissues","id"=>"74","kode_penyakit"=>"K04"),
            array("diagnosa"=>"Necrosis of pulp","id"=>"75","kode_penyakit"=>"K04.1"),
            array("diagnosa"=>"Schizophrenia","id"=>"76","kode_penyakit"=>"F20"),
            array("diagnosa"=>"Paranoid schizophrenia","id"=>"77","kode_penyakit"=>"F20.0"),
            array("diagnosa"=>"Atopic dermatitis","id"=>"78","kode_penyakit"=>"L20"),
            array("diagnosa"=>"Myalgia","id"=>"79","kode_penyakit"=>"M79.1"),
            array("diagnosa"=>"Other benign neoplasm of connective and other soft tissue of thorax Axilla","id"=>"80","kode_penyakit"=>"D21.3"),
            array("diagnosa"=>"Cutaneous abscess, furuncle and carbuncle","id"=>"81","kode_penyakit"=>"L02"),
            array("diagnosa"=>"Cutaneous abscess, furuncle and carbuncle of buttock","id"=>"82","kode_penyakit"=>"L02.3"),
            array("diagnosa"=>"Insulin-dependent diabetes mellitus with peripheral circulatory complications","id"=>"83","kode_penyakit"=>"E10.5"),
            array("diagnosa"=>"Hypertensive heart disease with (congestive) heart failure","id"=>"84","kode_penyakit"=>"I11.0"),
            array("diagnosa"=>"Influenza due to other identified influenza virus","id"=>"85","kode_penyakit"=>"J10"),
            array("diagnosa"=>"Neuralgia and neuritis, unspecified, forearm","id"=>"86","kode_penyakit"=>"M79.23"),
            array("diagnosa"=>"Anaesthesia of skin","id"=>"87","kode_penyakit"=>"R20.0"),
            array("diagnosa"=>"Other benign neoplasms of connective and other soft tissue","id"=>"88","kode_penyakit"=>"D21"),
            array("diagnosa"=>"Tuberculosis of larynx, trachea and bronchus, confirmed bacteriologically and histologically","id"=>"89","kode_penyakit"=>"A15.5"),
            array("diagnosa"=>"Malaise and fatigue","id"=>"90","kode_penyakit"=>"R53"),
            array("diagnosa"=>"Hyperkinetic disorder, unspecified","id"=>"91","kode_penyakit"=>"F90.9"),
            array("diagnosa"=>"Dysmenorrhoea, unspecified","id"=>"92","kode_penyakit"=>"N94.6"),
            array("diagnosa"=>"Other disorders of breast","id"=>"93","kode_penyakit"=>"N64"),
            array("diagnosa"=>"Enlarged lymph nodes","id"=>"94","kode_penyakit"=>"R59"),
            array("diagnosa"=>"Influenza, virus not identified","id"=>"95","kode_penyakit"=>"J11"),
            array("diagnosa"=>"Pure hypercholesterolaemia","id"=>"96","kode_penyakit"=>"E78.0"),
            array("diagnosa"=>"Urticaria","id"=>"97","kode_penyakit"=>"L50"),
            array("diagnosa"=>"Blighted ovum and nonhydatidiform mole","id"=>"98","kode_penyakit"=>"O02.0"),
            array("diagnosa"=>"Paraesthesia of skin","id"=>"99","kode_penyakit"=>"R20.2"),
            array("diagnosa"=>"Insulin-dependent diabetes mellitus with neurological complications","id"=>"100","kode_penyakit"=>"E10.4"),
            array("diagnosa"=>"Other dermatitis","id"=>"101","kode_penyakit"=>"L30"),
            array("diagnosa"=>"Polyarthritis, unspecified","id"=>"102","kode_penyakit"=>"M13.0"),
            array("diagnosa"=>"Mixed anxiety and depressive disorder","id"=>"103","kode_penyakit"=>"F41.2"),
            array("diagnosa"=>"Nephrotic syndrome","id"=>"104","kode_penyakit"=>"N04"),
            array("diagnosa"=>"Insulin-dependent diabetes mellitus without complications","id"=>"105","kode_penyakit"=>"E10.9"),
            array("diagnosa"=>"Myopia","id"=>"106","kode_penyakit"=>"H52.1"),
            array("diagnosa"=>"Migraine","id"=>"107","kode_penyakit"=>"G43"),
            array("diagnosa"=>"Pityriasis versicolor","id"=>"108","kode_penyakit"=>"B36.0"),
            array("diagnosa"=>"Scabies","id"=>"109","kode_penyakit"=>"B86"),
            array("diagnosa"=>"Congestive heart failure","id"=>"110","kode_penyakit"=>"I50.0"),
            array("diagnosa"=>"Non-insulin-dependent diabetes mellitus with other specified complications","id"=>"111","kode_penyakit"=>"E11.6"),
            array("diagnosa"=>"Impacted cerumen","id"=>"112","kode_penyakit"=>"H61.2"),
            array("diagnosa"=>"Other benign neoplasm of connective and other soft tissue of head, face and neck","id"=>"113","kode_penyakit"=>"D21.0"),
            array("diagnosa"=>"Anaemia, unspecified","id"=>"114","kode_penyakit"=>"D64.9"),
            array("diagnosa"=>"Tinea corporis","id"=>"115","kode_penyakit"=>"B35.4"),
            array("diagnosa"=>"Other acute upper respiratory infections of multiple sites","id"=>"116","kode_penyakit"=>"I50"),
            array("diagnosa"=>"Disorder of purine and pyrimidine metabolism, unspecified","id"=>"117","kode_penyakit"=>"E79.9"),
            array("diagnosa"=>"Urinary tract infection, site not specified","id"=>"118","kode_penyakit"=>" N39.0"),
            array("diagnosa"=>"Dyspepsia","id"=>"119","kode_penyakit"=>"K30"),
            array("diagnosa"=>"Non-insulin-dependent diabetes mellitus with neurological complications","id"=>"120","kode_penyakit"=>"E11.4"),
            array("diagnosa"=>"Non-insulin-dependent diabetes mellitus with ophthalmic complications","id"=>"121","kode_penyakit"=>"E11.3"),
            array("diagnosa"=>"Allergic contact dermatitis due to plants, except food","id"=>"122","kode_penyakit"=>"L23.7"),
            array("diagnosa"=>"Candidal stomatitis","id"=>"123","kode_penyakit"=>"B37.0"),
            array("diagnosa"=>"Chronic periodontitis","id"=>"124","kode_penyakit"=>"K05.3"),
            array("diagnosa"=>"Undifferentiated schizophrenia","id"=>"125","kode_penyakit"=>"F20.3"),
            array("diagnosa"=>"Hypermetropia","id"=>"126","kode_penyakit"=>"H52.0"),
            array("diagnosa"=>"Haemorrhoids","id"=>"127","kode_penyakit"=>"I84"),
            array("diagnosa"=>"Other benign neoplasm of connective and other soft tissue of abdomen","id"=>"128","kode_penyakit"=>"D21.4"),
            array("diagnosa"=>"Glaucoma","id"=>"129","kode_penyakit"=>"H40"),
            array("diagnosa"=>"Unstable angina","id"=>"130","kode_penyakit"=>"I20.0"),
            array("diagnosa"=>"Acute periodontitis","id"=>"131","kode_penyakit"=>"K05.2"),
            array("diagnosa"=>"Acute larynpharyngitis","id"=>"132","kode_penyakit"=>"J06.0"),
            array("diagnosa"=>"Verti of central origin","id"=>"133","kode_penyakit"=>"H81.4"),
            array("diagnosa"=>"Disorders of vestibular function","id"=>"134","kode_penyakit"=>"H81"),
            array("diagnosa"=>"Old myocardial infarction","id"=>"135","kode_penyakit"=>"I25.2"),
            array("diagnosa"=>"Periapical abscess without sinus","id"=>"136","kode_penyakit"=>"K04.7"),
            array("diagnosa"=>"Adhesive capsulitis of shoulder","id"=>"137","kode_penyakit"=>"M75.0"),
            array("diagnosa"=>"Scoliosis","id"=>"138","kode_penyakit"=>"M41"),
            array("diagnosa"=>"Sciatica, lumbosacral region","id"=>"139","kode_penyakit"=>"M54.37"),
            array("diagnosa"=>"Acute serous otitis media","id"=>"140","kode_penyakit"=>"H65.0"),
            array("diagnosa"=>"Other acute gastritis","id"=>"141","kode_penyakit"=>"K29.1"),
            array("diagnosa"=>"Cutaneous abscess, furuncle and carbuncle of other sites","id"=>"142","kode_penyakit"=>"L02.8"),
            array("diagnosa"=>"Zoster [herpes zoster]","id"=>"143","kode_penyakit"=>"B02"),
            array("diagnosa"=>"Fever of other and unknown origin","id"=>"144","kode_penyakit"=>"R50"),
            array("diagnosa"=>"Rheumatism, unspecified, shoulder region","id"=>"145","kode_penyakit"=>"M79.01"),
            array("diagnosa"=>"Hordeolum and chalazion","id"=>"146","kode_penyakit"=>"H00"),
            array("diagnosa"=>"Diplopia","id"=>"147","kode_penyakit"=>"H53.2"),
            array("diagnosa"=>"Allergic rhinitis, unspecified","id"=>"148","kode_penyakit"=>"J30.4"),
            array("diagnosa"=>"Inguinal hernia","id"=>"149","kode_penyakit"=>"K40"),
            array("diagnosa"=>"Schizoaffective disorders","id"=>"150","kode_penyakit"=>"F25"),
            array("diagnosa"=>"Secondary amenorrhoea","id"=>"151","kode_penyakit"=>"N91.1"),
            array("diagnosa"=>"Calculus of kidney","id"=>"152","kode_penyakit"=>"N20.0"),
            array("diagnosa"=>"Dislocation, sprain and strain of joints and ligaments of knee","id"=>"153","kode_penyakit"=>"S83"),
            array("diagnosa"=>"Psoriasis","id"=>"154","kode_penyakit"=>"L40"),
            array("diagnosa"=>"Cervical root disorders, not elsewhere classified","id"=>"155","kode_penyakit"=>"G54.2"),
            array("diagnosa"=>"Gastro-oesophageal reflux disease","id"=>"156","kode_penyakit"=>"K21"),
            array("diagnosa"=>"Nonspecific lymphadenitis","id"=>"157","kode_penyakit"=>"I88"),
            array("diagnosa"=>"Myalgia, shoulder region","id"=>"158","kode_penyakit"=>"M79.11"),
            array("diagnosa"=>"Carpal tunnel syndrome","id"=>"159","kode_penyakit"=>"G56.0"),
            array("diagnosa"=>"Vestibular neuronitis","id"=>"160","kode_penyakit"=>"H81.2"),
            array("diagnosa"=>"Allergy, unspecified","id"=>"161","kode_penyakit"=>"T78.4"),
            array("diagnosa"=>"Non-insulin-dependent diabetes mellitus with coma","id"=>"162","kode_penyakit"=>"E11.0"),
            array("diagnosa"=>"Leprosy [Hansen disease]","id"=>"163","kode_penyakit"=>"A30"),
            array("diagnosa"=>"Dizziness and giddiness","id"=>"164","kode_penyakit"=>"R42"),
            array("diagnosa"=>"Neuralgia and neuritis, unspecified, ankle and foot","id"=>"165","kode_penyakit"=>"M79.27"),
            array("diagnosa"=>"Cutaneous abscess, furuncle and carbuncle of limb","id"=>"166","kode_penyakit"=>"L02.4"),
            array("diagnosa"=>"Constipation","id"=>"167","kode_penyakit"=>"K59.0"),
            array("diagnosa"=>"Periapical abscess with sinus","id"=>"168","kode_penyakit"=>"K04.6"),
            array("diagnosa"=>"Respiratory tuberculosis, bacteriologically and histologically confirmed","id"=>"169","kode_penyakit"=>"A15"),
            array("diagnosa"=>"Acute bronchitis","id"=>"170","kode_penyakit"=>"J20"),
            array("diagnosa"=>"Other allergic rhinitis","id"=>"171","kode_penyakit"=>"J30.3"),
            array("diagnosa"=>"Mumps","id"=>"172","kode_penyakit"=>"B26"),
            array("diagnosa"=>"Migraine without aura [common migraine]","id"=>"173","kode_penyakit"=>"G43.0"),
            array("diagnosa"=>"Thrombocytopenia, unspecified","id"=>"174","kode_penyakit"=>"D69.6"),
            array("diagnosa"=>"Other forms of stomatitis","id"=>"175","kode_penyakit"=>"K12.1"),
            array("diagnosa"=>"Other disorders of purine and pyrimidine metabolism","id"=>"176","kode_penyakit"=>"E79.8"),
            array("diagnosa"=>"Neuralgia and neuritis, unspecified, pelvic and thigh","id"=>"177","kode_penyakit"=>"M79.25"),
            array("diagnosa"=>"Cellulitis of finger and toe","id"=>"178","kode_penyakit"=>"L03.0"),
            array("diagnosa"=>"Pterygium","id"=>"179","kode_penyakit"=>"H11.0"),
            array("diagnosa"=>"Other anxiety disorders","id"=>"180","kode_penyakit"=>"F41"),
            array("diagnosa"=>"Other gastritis","id"=>"181","kode_penyakit"=>"K29.6"),
            array("diagnosa"=>"Cholelithiasis","id"=>"182","kode_penyakit"=>"K80"),
            array("diagnosa"=>"Tinnitus","id"=>"183","kode_penyakit"=>"H93.1"),
            array("diagnosa"=>"Bronchopneumonia, unspecified","id"=>"184","kode_penyakit"=>"J18.0"),
            array("diagnosa"=>"Human immunodeficiency virus [HIV] disease resulting in infectious and parasitic diseases","id"=>"185","kode_penyakit"=>"B20"),
            array("diagnosa"=>"Tinea barbae and tinea capitis","id"=>"186","kode_penyakit"=>"B35.0"),
            array("diagnosa"=>"Asthma, unspecified","id"=>"187","kode_penyakit"=>"J45.9"),
            array("diagnosa"=>"Enteroviral vesicular stomatitis with exanthem","id"=>"188","kode_penyakit"=>"B08.4"),
            array("diagnosa"=>"Neuralgia and neuritis, unspecified, hand","id"=>"189","kode_penyakit"=>"M79.24"),
            array("diagnosa"=>"Ganglion","id"=>"190","kode_penyakit"=>"M67.4"),
            array("diagnosa"=>"Tinea pedis","id"=>"191","kode_penyakit"=>"B35.3"),
            array("diagnosa"=>"Parkinson's disease","id"=>"192","kode_penyakit"=>"G20"),
            array("diagnosa"=>"Low back pain, multiple sites","id"=>"193","kode_penyakit"=>"M54.50"),
            array("diagnosa"=>"Bipolar affective disorder, current episode manic with psychotic symptoms","id"=>"194","kode_penyakit"=>"F31.2"),
            array("diagnosa"=>"Dyspnoea","id"=>"195","kode_penyakit"=>"R06.0"),
            array("diagnosa"=>"Acute tonsillitis","id"=>"196","kode_penyakit"=>"J03"),
            array("diagnosa"=>"Infective dermatitis","id"=>"197","kode_penyakit"=>"L30.3"),
            array("diagnosa"=>"Other soft tissue disorders, not elsewhere classified","id"=>"198","kode_penyakit"=>"M79"),
            array("diagnosa"=>"Calculus of kidney and ureter","id"=>"199","kode_penyakit"=>"N20"),
            array("diagnosa"=>"Bipolar affective disorder, current episode manic without psychotic symptoms","id"=>"200","kode_penyakit"=>"F31.1"),
            array("diagnosa"=>"Specific developmental disorders of speech and language","id"=>"201","kode_penyakit"=>"F80"),
            array("diagnosa"=>"Coronavirus infection, unspecified","id"=>"202","kode_penyakit"=>"B34.2"),
            array("diagnosa"=>"Other viral infections characterized by skin and mucous membrane lesions, not elsewhere classified","id"=>"203","kode_penyakit"=>"B08"),
            array("diagnosa"=>"Dengue haemorrhagic fever","id"=>"204","kode_penyakit"=>"A91"),
            array("diagnosa"=>"Otitis externa","id"=>"205","kode_penyakit"=>"H60"),
            array("diagnosa"=>"Hyphaema","id"=>"206","kode_penyakit"=>"H21.0"),
            array("diagnosa"=>"Keratitis","id"=>"207","kode_penyakit"=>"H16"),
            array("diagnosa"=>"Tinea cruris","id"=>"208","kode_penyakit"=>"B35.6"),
            array("diagnosa"=>"Chronic atrophic gastritis","id"=>"209","kode_penyakit"=>"K29.4"),
            array("diagnosa"=>"Blepharitis","id"=>"210","kode_penyakit"=>"H01.0"),
            array("diagnosa"=>"Other and unspecified abdominal pain","id"=>"211","kode_penyakit"=>"R10.4"),
            array("diagnosa"=>"Myalgia, multiple sites","id"=>"212","kode_penyakit"=>"M79.10"),
            array("diagnosa"=>"Neuralgia and neuritis, unspecified, upper arm","id"=>"213","kode_penyakit"=>"M79.22"),
            array("diagnosa"=>"Pain localized to other parts of lower abdomen","id"=>"214","kode_penyakit"=>"R10.3"),
            array("diagnosa"=>"Stroke, not specified as haemorrhage or infarction","id"=>"215","kode_penyakit"=>"I64"),
            array("diagnosa"=>"Vertiginous syndromes in diseases classified elsewhere","id"=>"216","kode_penyakit"=>"H82"),
            array("diagnosa"=>"Radiculopathy","id"=>"217","kode_penyakit"=>"M54.1"),
            array("diagnosa"=>"Hordeolum and other deep inflammation of eyelid","id"=>"218","kode_penyakit"=>"H00.0"),
            array("diagnosa"=>"Rheumatism, unspecified, forearm","id"=>"219","kode_penyakit"=>"M79.03"),
            array("diagnosa"=>"Insulin-dependent diabetes mellitus","id"=>"220","kode_penyakit"=>"E10"),
            array("diagnosa"=>"External haemorrhoids with other complications","id"=>"221","kode_penyakit"=>"I84.4"),
            array("diagnosa"=>"Rheumatism, unspecified, multiple sites","id"=>"222","kode_penyakit"=>"M79.00"),
            array("diagnosa"=>"Deposits [accretions] on teeth","id"=>"223","kode_penyakit"=>"K03.6"),
            array("diagnosa"=>"Other specified injuries of thorax","id"=>"224","kode_penyakit"=>"S29.8"),
            array("diagnosa"=>"Ventricular septal defect","id"=>"225","kode_penyakit"=>"Q21.0"),
            array("diagnosa"=>"Corns and callosities","id"=>"226","kode_penyakit"=>"L84"),
            array("diagnosa"=>"Syncope and collapse","id"=>"227","kode_penyakit"=>"R55"),
            array("diagnosa"=>"Haemoptysis","id"=>"228","kode_penyakit"=>"R04.2"),
            array("diagnosa"=>"Other bursopathies","id"=>"229","kode_penyakit"=>"M71"),
            array("diagnosa"=>"Prolonged pregnancy","id"=>"230","kode_penyakit"=>"O48"),
            array("diagnosa"=>"Stomatitis and related lesions","id"=>"231","kode_penyakit"=>"K12"),
            array("diagnosa"=>"Myalgia, ankle and foot","id"=>"232","kode_penyakit"=>"M79.17"),
            array("diagnosa"=>"Arteritis, unspecified","id"=>"233","kode_penyakit"=>"I77.6"),
            array("diagnosa"=>"Other epilepsy","id"=>"234","kode_penyakit"=>"G40.8"),
            array("diagnosa"=>"Sequelae of cerebrovascular disease","id"=>"235","kode_penyakit"=>"I69"),
            array("diagnosa"=>"Conjunctivitis, unspecified","id"=>"236","kode_penyakit"=>"H10.9"),
            array("diagnosa"=>"Candidiasis of other urogenital sites","id"=>"237","kode_penyakit"=>"B37.4"),
            array("diagnosa"=>"Abdominal and pelvic pain","id"=>"238","kode_penyakit"=>"R10"),
            array("diagnosa"=>"Retained dental root","id"=>"239","kode_penyakit"=>"K08.3"),
            array("diagnosa"=>"Meniere's disease","id"=>"240","kode_penyakit"=>"H81.0"),
            array("diagnosa"=>"Hyperplasia of prostate","id"=>"241","kode_penyakit"=>"N40"),
            array("diagnosa"=>"Non-Hodgkin's lymphoma, unspecified type","id"=>"242","kode_penyakit"=>"C85.9"),
            array("diagnosa"=>"Gastritis and duodenitis","id"=>"243","kode_penyakit"=>"K29"),
            array("diagnosa"=>"Thyrotoxicosis with diffuse itre","id"=>"244","kode_penyakit"=>"E05.0"),
            array("diagnosa"=>"Other chronic cystitis","id"=>"245","kode_penyakit"=>"N30.2"),
            array("diagnosa"=>"Open wound of unspecified body region","id"=>"246","kode_penyakit"=>"T14.1"),
            array("diagnosa"=>"Tachycardia, unspecified","id"=>"247","kode_penyakit"=>"R00.0"),
            array("diagnosa"=>"Polyarthritis, unspecified, unspecified site","id"=>"248","kode_penyakit"=>"M13.09"),
            array("diagnosa"=>"Disturbance of activity and attention","id"=>"249","kode_penyakit"=>"F90.0"),
            array("diagnosa"=>"Other specified respiratory disorders","id"=>"250","kode_penyakit"=>"J98.8"),
            array("diagnosa"=>"Herpesviral [herpes simplex] infections","id"=>"251","kode_penyakit"=>"B00"),
            array("diagnosa"=>"narthrosis, unspecified","id"=>"252","kode_penyakit"=>"M17.9"),
            array("diagnosa"=>"Premature rupture of membranes","id"=>"253","kode_penyakit"=>"O42"),
            array("diagnosa"=>"Myalgia, lower leg","id"=>"254","kode_penyakit"=>"M79.16"),
            array("diagnosa"=>"Mucopurulent conjunctivitis","id"=>"255","kode_penyakit"=>"H10.0"),
            array("diagnosa"=>"Cutaneous abscess, furuncle and carbuncle of face","id"=>"256","kode_penyakit"=>"L02.0"),
            array("diagnosa"=>"Vitili","id"=>"257","kode_penyakit"=>"L80"),
            array("diagnosa"=>"Polyp of nasal cavity","id"=>"258","kode_penyakit"=>"J33.0"),
            array("diagnosa"=>"Unspecified haemorrhoids with other complications","id"=>"259","kode_penyakit"=>"I84.8"),
            array("diagnosa"=>"Gastro-oesophageal reflux disease with oesophagitis","id"=>"260","kode_penyakit"=>"K21.0"),
            array("diagnosa"=>"Acquired stenosis of external ear canal","id"=>"261","kode_penyakit"=>"H61.3"),
            array("diagnosa"=>"Depressive episode","id"=>"262","kode_penyakit"=>"F32"),
            array("diagnosa"=>"Cellulitis of other parts of limb","id"=>"263","kode_penyakit"=>"L03.1"),
            array("diagnosa"=>"Suppurative and unspecified otitis media","id"=>"264","kode_penyakit"=>"H66"),
            array("diagnosa"=>"Malignant neoplasm of bladder","id"=>"265","kode_penyakit"=>"C67"),
            array("diagnosa"=>"Acute pharyngitis","id"=>"266","kode_penyakit"=>"S00"),
            array("diagnosa"=>"Superficial injury of scalp","id"=>"267","kode_penyakit"=>"S00.0"),
            array("diagnosa"=>"Contusion of eyelid and periocular area","id"=>"268","kode_penyakit"=>"S00.1"),
            array("diagnosa"=>"Hypertensive heart disease","id"=>"269","kode_penyakit"=>"I11"),
            array("diagnosa"=>"Allergic contact dermatitis due to cosmetics","id"=>"270","kode_penyakit"=>"L23.2"),
            array("diagnosa"=>"Seborrhoeic dermatitis","id"=>"271","kode_penyakit"=>"L21"),
            array("diagnosa"=>"Otalgia","id"=>"272","kode_penyakit"=>"H92.0"),
            array("diagnosa"=>"Candidiasis of vulva and vagina","id"=>"273","kode_penyakit"=>"B37.3"),
            array("diagnosa"=>"Chronic kidney disease, stage 2","id"=>"274","kode_penyakit"=>"N18.2"),
            array("diagnosa"=>"Superficial frostbite of knee and lower leg","id"=>"275","kode_penyakit"=>"T33.7"),
            array("diagnosa"=>"Other and unspecified gastroenteritis and colitis of infectious origin","id"=>"276","kode_penyakit"=>"A09.0"),
            array("diagnosa"=>"Low back pain, lumbar region","id"=>"277","kode_penyakit"=>"M54.56"),
            array("diagnosa"=>"Malignant neoplasm of cervix uteri, unspecified","id"=>"278","kode_penyakit"=>"C53.9"),
            array("diagnosa"=>"Onycholysis","id"=>"279","kode_penyakit"=>"L60.1"),
            array("diagnosa"=>"Seborrhoeic keratosis","id"=>"280","kode_penyakit"=>"L82"),
            array("diagnosa"=>"Other and unspecified cirrhosis of liver","id"=>"281","kode_penyakit"=>"K74.6"),
            array("diagnosa"=>"Bacterial pneumonia, not elsewhere classified","id"=>"282","kode_penyakit"=>"J15"),
            array("diagnosa"=>"Meralgia paraesthetica","id"=>"283","kode_penyakit"=>"G57.1"),
            array("diagnosa"=>"Acute sinusitis, unspecified","id"=>"284","kode_penyakit"=>"J01.9"),
            array("diagnosa"=>"Myalgia, other site","id"=>"285","kode_penyakit"=>"M79.18"),
            array("diagnosa"=>"Allergic contact dermatitis due to food in contact with skin","id"=>"286","kode_penyakit"=>"L23.6"),
            array("diagnosa"=>"Lesion of sciatic nerve","id"=>"287","kode_penyakit"=>"G57.0"),
            array("diagnosa"=>"Malignant neoplasm of skin of ear and external auricular canal","id"=>"288","kode_penyakit"=>"C44.2"),
            array("diagnosa"=>"Disruption of perineal obstetric wound","id"=>"289","kode_penyakit"=>"O90.1"),
            array("diagnosa"=>"Malignant neoplasm of glottis","id"=>"290","kode_penyakit"=>"C32.0"),
            array("diagnosa"=>"Chronic viral hepatitis B without delta-agent","id"=>"291","kode_penyakit"=>"B18.1"),
            array("diagnosa"=>"Dengue fever [classical dengue]","id"=>"292","kode_penyakit"=>"A90"),
            array("diagnosa"=>"Pyoderma","id"=>"293","kode_penyakit"=>"L08.0"),
            array("diagnosa"=>"Polyarthrosis","id"=>"294","kode_penyakit"=>"M15"),
            array("diagnosa"=>"Bilateral inguinal hernia, with gangrene","id"=>"295","kode_penyakit"=>"K40.1"),
            array("diagnosa"=>"Xerosis cutis","id"=>"296","kode_penyakit"=>"L85.3"),
            array("diagnosa"=>"Other polyneuropathies","id"=>"297","kode_penyakit"=>"G62"),
            array("diagnosa"=>"Panniculitis affecting regions of neck and back, lumbar region","id"=>"298","kode_penyakit"=>"M54.06"),
            array("diagnosa"=>"Other headache syndromes","id"=>"299","kode_penyakit"=>"G44"),
            array("diagnosa"=>"Other dissociative [conversion] disorders","id"=>"300","kode_penyakit"=>"F44.8"),
            array("diagnosa"=>"Tetralogy of Fallot","id"=>"301","kode_penyakit"=>"Q21.3"),
            array("diagnosa"=>"Miliaria, unspecified","id"=>"302","kode_penyakit"=>"L74.3"),
            array("diagnosa"=>"Other hydrocele","id"=>"303","kode_penyakit"=>"N43.2"),
            array("diagnosa"=>"Other hyperlipidaemia","id"=>"304","kode_penyakit"=>"E78.4"),
            array("diagnosa"=>"Other disorders of external ear","id"=>"305","kode_penyakit"=>"H61"),
            array("diagnosa"=>"Malignant neoplasm of larynx, unspecified","id"=>"306","kode_penyakit"=>"C32.9"),
            array("diagnosa"=>"Allergic urticaria","id"=>"307","kode_penyakit"=>"L50.0"),
            array("diagnosa"=>"Mononeuropathy of lower limb, unspecified","id"=>"308","kode_penyakit"=>"G57.9"),
            array("diagnosa"=>"Other retinal disorders","id"=>"309","kode_penyakit"=>"H35"),
            array("diagnosa"=>"Hereditary retinal dystrophy","id"=>"310","kode_penyakit"=>"H35.5"),
            array("diagnosa"=>"Other proliferative retinopathy","id"=>"311","kode_penyakit"=>"H35.2"),
            array("diagnosa"=>"Diabetic retinopathy","id"=>"312","kode_penyakit"=>"H36.0"),
            array("diagnosa"=>"Pneumonia, organism unspecified","id"=>"313","kode_penyakit"=>"J18"),
            array("diagnosa"=>"Other and unspecified disorders of circulatory system","id"=>"314","kode_penyakit"=>"I99"),
            array("diagnosa"=>"Other specified disorders of conjunctiva","id"=>"315","kode_penyakit"=>"H11.8"),
            array("diagnosa"=>"Gastric ulcer","id"=>"316","kode_penyakit"=>"K25"),
            array("diagnosa"=>"Community Acquired Pneumonia","id"=>"317","kode_penyakit"=>"J18.90"),
            array("diagnosa"=>"Dental caries","id"=>"318","kode_penyakit"=>"K02"),
            array("diagnosa"=>"Other abnormal products of conception","id"=>"319","kode_penyakit"=>"O02"),
            array("diagnosa"=>"Atresia of bile ducts","id"=>"320","kode_penyakit"=>"Q44.2"),
            array("diagnosa"=>"Dermatophytosis","id"=>"321","kode_penyakit"=>"B35"),
            array("diagnosa"=>"Allergic contact dermatitis, unspecified cause","id"=>"322","kode_penyakit"=>"L23.9"),
            array("diagnosa"=>"Maternal care for other known or suspected fetal problems","id"=>"323","kode_penyakit"=>"O36"),
            array("diagnosa"=>"Other malignant neoplasms of skin","id"=>"324","kode_penyakit"=>"C44"),
            array("diagnosa"=>"Ptosis of eyelid","id"=>"325","kode_penyakit"=>"H02.4"),
            array("diagnosa"=>"Unspecified dementia","id"=>"326","kode_penyakit"=>"F03"),
            array("diagnosa"=>"Dorsalgia","id"=>"327","kode_penyakit"=>"M54"),
            array("diagnosa"=>"Candidiasis of skin and nail","id"=>"328","kode_penyakit"=>"B37.2"),
            array("diagnosa"=>"Chronic gingivitis","id"=>"329","kode_penyakit"=>"K05.1"),
            array("diagnosa"=>"Purpura and other haemorrhagic conditions","id"=>"330","kode_penyakit"=>"D69"),
            array("diagnosa"=>"Sprain and strain of other and unspecified parts of shoulder girdle","id"=>"331","kode_penyakit"=>"S43.7"),
            array("diagnosa"=>"Bladder disorders in diseases classified elsewhere","id"=>"332","kode_penyakit"=>"N33"),
            array("diagnosa"=>"Haemorrhage and haematoma complicating a procedure, not elsewhere classified","id"=>"333","kode_penyakit"=>"T81.0"),
            array("diagnosa"=>"Muscle strain","id"=>"334","kode_penyakit"=>"M62.6"),
            array("diagnosa"=>"Muscle strain, ankle and foot","id"=>"335","kode_penyakit"=>"M62.67"),
            array("diagnosa"=>"Osteophyte, ankle and foot","id"=>"336","kode_penyakit"=>"M25.77"),
            array("diagnosa"=>"Pruritus","id"=>"337","kode_penyakit"=>"L29"),
            array("diagnosa"=>"Tinea unguium","id"=>"338","kode_penyakit"=>"B35.1"),
            array("diagnosa"=>"Foreign body granuloma of soft tissue, pelvic region and thigh","id"=>"339","kode_penyakit"=>"M60.25"),
            array("diagnosa"=>"Acute lymphadenitis, unspecified","id"=>"340","kode_penyakit"=>"L04.9"),
            array("diagnosa"=>"Acute cystitis","id"=>"341","kode_penyakit"=>"N30.0"),
            array("diagnosa"=>"Motion sickness","id"=>"342","kode_penyakit"=>"T75.3"),
            array("diagnosa"=>"Other and unspecified ovarian cysts","id"=>"343","kode_penyakit"=>"N83.2"),
            array("diagnosa"=>"Acute gastroenteropathy due to Norwalk agent","id"=>"344","kode_penyakit"=>"A08.1"),
            array("diagnosa"=>"Acute laryngitis","id"=>"345","kode_penyakit"=>"J04.0"),
            array("diagnosa"=>"Atherosclerotic heart disease","id"=>"346","kode_penyakit"=>"I25.1"),
            array("diagnosa"=>"Varicose veins of other sites","id"=>"347","kode_penyakit"=>"I86"),
            array("diagnosa"=>"Hyperglycaemia, unspecified","id"=>"348","kode_penyakit"=>"R73.9"),
            array("diagnosa"=>"Malignant neoplasm of prostate","id"=>"349","kode_penyakit"=>"C61"),
            array("diagnosa"=>"Sciatica, multiple sites","id"=>"350","kode_penyakit"=>"M54.30"),
            array("diagnosa"=>"Acute ethmoidal sinusitis","id"=>"351","kode_penyakit"=>"J01.2"),
            array("diagnosa"=>"Thalassaemia","id"=>"352","kode_penyakit"=>"D56"),
            array("diagnosa"=>"Moderate depressive episode","id"=>"353","kode_penyakit"=>"F32.1"),
            array("diagnosa"=>"Sprain and strain of other and unspecified parts of foot","id"=>"354","kode_penyakit"=>"S93.6"),
            array("diagnosa"=>"Acute lymphadenitis","id"=>"355","kode_penyakit"=>"L04"),
            array("diagnosa"=>"Acute lymphadenitis of other sites","id"=>"356","kode_penyakit"=>"L04.8"),
            array("diagnosa"=>"Acute lymphadenitis of face, head and neck","id"=>"357","kode_penyakit"=>"L04.0"),
            array("diagnosa"=>"Acute and transient psychotic disorder, unspecified","id"=>"358","kode_penyakit"=>"F23.9"),
            array("diagnosa"=>"Other peripheral verti","id"=>"359","kode_penyakit"=>"H81.3"),
            array("diagnosa"=>"Migraine with aura [classical migraine]","id"=>"360","kode_penyakit"=>"G43.1"),
            array("diagnosa"=>"Radial styloid tenosynovitis [de Quervain]","id"=>"361","kode_penyakit"=>"M65.4"),
            array("diagnosa"=>"Amblyopia ex anopsia","id"=>"362","kode_penyakit"=>"H53.0"),
            array("diagnosa"=>"Sprain and strain of other and unspecified parts of knee","id"=>"363","kode_penyakit"=>"S83.6"),
            array("diagnosa"=>"Spastic paraplegia","id"=>"364","kode_penyakit"=>"G82.1"),
            array("diagnosa"=>"Generalized idiopathic epilepsy and epileptic syndromes","id"=>"365","kode_penyakit"=>"G40.3"),
            array("diagnosa"=>"Allergic rhinitis due to pollen","id"=>"366","kode_penyakit"=>"J30.1"),
            array("diagnosa"=>"Low back pain, thoracolumbar region","id"=>"367","kode_penyakit"=>"M54.55"),
            array("diagnosa"=>"Superficial injury of unspecified body region","id"=>"368","kode_penyakit"=>"T14.0"),
            array("diagnosa"=>"Viral conjunctivitis","id"=>"369","kode_penyakit"=>"B30"),
            array("diagnosa"=>"Acute epidemic haemorrhagic conjunctivitis (enteroviral)","id"=>"370","kode_penyakit"=>"B30.3"),
            array("diagnosa"=>"Conjunctivitis due to adenovirus","id"=>"371","kode_penyakit"=>"B30.1"),
            array("diagnosa"=>"Rheumatism, unspecified, upper arm","id"=>"372","kode_penyakit"=>"M79.02"),
            array("diagnosa"=>"Benign lipomatous neoplasm of other sites","id"=>"373","kode_penyakit"=>"D17.7"),
            array("diagnosa"=>"Dislocation, sprain and strain of joints and ligaments of elbow","id"=>"374","kode_penyakit"=>"S53"),
            array("diagnosa"=>"Bell's palsy","id"=>"375","kode_penyakit"=>"G51.0"),
            array("diagnosa"=>"Other specified fever","id"=>"376","kode_penyakit"=>"R50.8"),
            array("diagnosa"=>"Superficial injury of lower leg","id"=>"377","kode_penyakit"=>"S80"),
            array("diagnosa"=>"Fistula of intestine","id"=>"378","kode_penyakit"=>"K63.2"),
            array("diagnosa"=>"Mononeuropathies of upper limb","id"=>"379","kode_penyakit"=>"G56"),
            array("diagnosa"=>"Mixed conductive and sensorineural hearing loss, bilateral","id"=>"380","kode_penyakit"=>"H90.6"),
            array("diagnosa"=>"Nasal polyp","id"=>"381","kode_penyakit"=>"J33"),
            array("diagnosa"=>"Epidural haemorrhage","id"=>"382","kode_penyakit"=>"S06.4"),
            array("diagnosa"=>"Neuropathic spondylopathy","id"=>"383","kode_penyakit"=>"M49.4"),
            array("diagnosa"=>"Other specified dermatitis","id"=>"384","kode_penyakit"=>"L30.8"),
            array("diagnosa"=>"Orthostatic hypotension","id"=>"385","kode_penyakit"=>"I95.1"),
            array("diagnosa"=>"Other specified anaemias","id"=>"386","kode_penyakit"=>"D64.8"),
            array("diagnosa"=>"Scleritis","id"=>"387","kode_penyakit"=>"H15.0"),
            array("diagnosa"=>"Retarded development following protein-energy malnutrition","id"=>"388","kode_penyakit"=>"E45"),
            array("diagnosa"=>"Melaena","id"=>"389","kode_penyakit"=>"K92.1"),
            array("diagnosa"=>"Cystitis, unspecified","id"=>"390","kode_penyakit"=>"N30.9"),
            array("diagnosa"=>"Burn of second degree of head and neck","id"=>"391","kode_penyakit"=>"T20.2"),
            array("diagnosa"=>"Burns involving less than 10% of body surface","id"=>"392","kode_penyakit"=>"T31.0"),
            array("diagnosa"=>"Malignant neoplasm of colon","id"=>"393","kode_penyakit"=>"C18"),
            array("diagnosa"=>"Systemic lupus erythematosus","id"=>"394","kode_penyakit"=>"M32"),
            array("diagnosa"=>"Other benign neoplasm of connective and other soft tissue of upper limb, including shoulder","id"=>"395","kode_penyakit"=>"D21.1"),
            array("diagnosa"=>"Leptospirosis","id"=>"396","kode_penyakit"=>"A27"),
            array("diagnosa"=>"Unspecified contact dermatitis","id"=>"397","kode_penyakit"=>"L25"),
            array("diagnosa"=>"Other specified noninflammatory disorders of vagina","id"=>"398","kode_penyakit"=>"N89.8"),
            array("diagnosa"=>"Hyperkinetic disorders","id"=>"399","kode_penyakit"=>"F90"),
            array("diagnosa"=>"Injury of muscles and tendons of unspecified body region","id"=>"400","kode_penyakit"=>"T14.6"),
            array("diagnosa"=>"Benign neoplasm of brain and other parts of central nervous system","id"=>"401","kode_penyakit"=>"D33"),
            array("diagnosa"=>"Benign neoplasm of brain, unspecified","id"=>"402","kode_penyakit"=>"D33.2"),
            array("diagnosa"=>"Benign lipomatous neoplasm","id"=>"403","kode_penyakit"=>"D17"),
            array("diagnosa"=>"Benign lipomatous neoplasm of skin and subcutaneous tissue of head, face and neck","id"=>"404","kode_penyakit"=>"D17.0"),
            array("diagnosa"=>"Impeti","id"=>"405","kode_penyakit"=>"L01"),
            array("diagnosa"=>"Ventral hernia with obstruction, without gangrene","id"=>"406","kode_penyakit"=>"K43.0"),
            array("diagnosa"=>"Other senile cataract","id"=>"407","kode_penyakit"=>"H25.8"),
            array("diagnosa"=>"Presbyopia","id"=>"408","kode_penyakit"=>"H52.4"),
            array("diagnosa"=>"Toxic effect of contact with venomous animals","id"=>"409","kode_penyakit"=>"T63"),
            array("diagnosa"=>"Conductive and sensorineural hearing loss","id"=>"410","kode_penyakit"=>"H90"),
            array("diagnosa"=>"Sensorineural hearing loss, unilateral with unrestricted hearing on the contralateral side","id"=>"411","kode_penyakit"=>"H90.4"),
            array("diagnosa"=>"Sensorineural hearing loss, unspecified","id"=>"412","kode_penyakit"=>"H90.5"),
            array("diagnosa"=>"Unilateral or unspecified inguinal hernia, with gangrene","id"=>"413","kode_penyakit"=>"K40.4"),
            array("diagnosa"=>"Haematemesis","id"=>"414","kode_penyakit"=>"K92.0"),
            array("diagnosa"=>"Other acute ischaemic heart diseases","id"=>"415","kode_penyakit"=>"I24"),
            array("diagnosa"=>"Other rheumatoid arthritis","id"=>"416","kode_penyakit"=>"M06"),
            array("diagnosa"=>"Other specified rheumatoid arthritis","id"=>"417","kode_penyakit"=>"M06.8"),
            array("diagnosa"=>"Inflammatory polyneuropathy","id"=>"418","kode_penyakit"=>"G61"),
            array("diagnosa"=>"Mania without psychotic symptoms","id"=>"419","kode_penyakit"=>"F30.1"),
            array("diagnosa"=>"Panic disorder [episodic paroxysmal anxiety]","id"=>"420","kode_penyakit"=>"F41.0"),
            array("diagnosa"=>"Malignant neoplasm of thyroid gland","id"=>"421","kode_penyakit"=>"C73"),
            array("diagnosa"=>"Atrial fibrillation and flutter","id"=>"422","kode_penyakit"=>"I48"),
            array("diagnosa"=>"Other specified chronic obstructive pulmonary disease","id"=>"423","kode_penyakit"=>"J44.8"),
            array("diagnosa"=>"Chronic tonsillitis","id"=>"424","kode_penyakit"=>"J35.0"),
            array("diagnosa"=>"Mechanical complication of intrauterine contraceptive device","id"=>"425","kode_penyakit"=>"T83.3"),
            array("diagnosa"=>"Tuberculosis of lung, confirmed by unspecified means","id"=>"426","kode_penyakit"=>"A15.3"),
            array("diagnosa"=>"Polyneuropathy in diseases classified elsewhere","id"=>"427","kode_penyakit"=>"G63"),
            array("diagnosa"=>"Spontaneous abortion","id"=>"428","kode_penyakit"=>"O03"),
            array("diagnosa"=>"Low vision, both eyes","id"=>"429","kode_penyakit"=>"H54.2"),
            array("diagnosa"=>"Spontaneous abortion, incomplete, without complication","id"=>"430","kode_penyakit"=>"O03.4"),
            array("diagnosa"=>"Neuralgia and neuritis, unspecified, other site","id"=>"431","kode_penyakit"=>"M79.28"),
            array("diagnosa"=>"Haemorrhage of anus and rectum","id"=>"432","kode_penyakit"=>"K62.5"),
            array("diagnosa"=>"Sprain and strain of ankle","id"=>"433","kode_penyakit"=>"S93.4"),
            array("diagnosa"=>"Other peripheral vascular diseases","id"=>"434","kode_penyakit"=>"I73"),
            array("diagnosa"=>"Disorders of lipoprotein metabolism and other lipidaemias","id"=>"435","kode_penyakit"=>"E78"),
            array("diagnosa"=>"Disorders of initiating and maintaining sleep [insomnias]","id"=>"436","kode_penyakit"=>"G47.0"),
            array("diagnosa"=>"Other disorders of binocular movement","id"=>"437","kode_penyakit"=>"H51"),
            array("diagnosa"=>"Hyperchylomicronaemia","id"=>"438","kode_penyakit"=>"E78.3"),
            array("diagnosa"=>"Tuberculosis of lung, bacteriologically and histologically negative","id"=>"439","kode_penyakit"=>"A16.0"),
            array("diagnosa"=>"Hemiplegia, unspecified","id"=>"440","kode_penyakit"=>"G81.9"),
            array("diagnosa"=>"Cellulitis of other sites","id"=>"441","kode_penyakit"=>"L03.8"),
            array("diagnosa"=>"Malignant neoplasm of breast","id"=>"442","kode_penyakit"=>"C50"),
            array("diagnosa"=>"Subjective visual disturbances","id"=>"443","kode_penyakit"=>"H53.1"),
            array("diagnosa"=>"Nontoxic single thyroid nodule","id"=>"444","kode_penyakit"=>"E04.1"),
            array("diagnosa"=>"Glaucoma suspect","id"=>"445","kode_penyakit"=>"H40.0"),
            array("diagnosa"=>"Tuberculosis of lung, confirmed histologically","id"=>"446","kode_penyakit"=>"A15.2"),
            array("diagnosa"=>"Candidiasis","id"=>"447","kode_penyakit"=>"B37"),
            array("diagnosa"=>"Other noninfective gastroenteritis and colitis","id"=>"448","kode_penyakit"=>"K52"),
            array("diagnosa"=>"Hypertrophy of adenoids","id"=>"449","kode_penyakit"=>"J35.2"),
            array("diagnosa"=>"Other lack of expected normal physiological development","id"=>"450","kode_penyakit"=>"R62.8"),
            array("diagnosa"=>"Other mononeuropathies","id"=>"451","kode_penyakit"=>"G58"),
            array("diagnosa"=>"Mononeuropathy, unspecified","id"=>"452","kode_penyakit"=>"G58.9"),
            array("diagnosa"=>"External thrombosed haemorrhoids","id"=>"453","kode_penyakit"=>"I84.3"),
            array("diagnosa"=>"Female genital prolapse","id"=>"454","kode_penyakit"=>"N81"),
            array("diagnosa"=>"Abrasion of teeth","id"=>"455","kode_penyakit"=>"K03.1"),
            array("diagnosa"=>"Acute gingivitis","id"=>"456","kode_penyakit"=>"K05.0"),
            array("diagnosa"=>"Other migraine","id"=>"457","kode_penyakit"=>"G43.8"),
            array("diagnosa"=>"Paratyphoid fever A","id"=>"458","kode_penyakit"=>"A01.1"),
            array("diagnosa"=>"Benign neoplasm of larynx","id"=>"459","kode_penyakit"=>"D14.1"),
            array("diagnosa"=>"Other superficial mycoses","id"=>"460","kode_penyakit"=>"B36"),
            array("diagnosa"=>"Tinea nigra","id"=>"461","kode_penyakit"=>"B36.1"),
            array("diagnosa"=>"Superficial mycosis, unspecified","id"=>"462","kode_penyakit"=>"B36.9"),
            array("diagnosa"=>"Chorioretinal inflammation","id"=>"463","kode_penyakit"=>"H30"),
            array("diagnosa"=>"Abnormal uterine and vaginal bleeding, unspecified","id"=>"464","kode_penyakit"=>"N93.9"),
            array("diagnosa"=>"Intracranial injury, unspecified","id"=>"465","kode_penyakit"=>"S06.9"),
            array("diagnosa"=>"Other benign neoplasm of other parts of uterus","id"=>"466","kode_penyakit"=>"D26.7"),
            array("diagnosa"=>"Sciatica, thoracolumbar region","id"=>"467","kode_penyakit"=>"M54.35"),
            array("diagnosa"=>"Insulin-dependent diabetes mellitus with other specified complications","id"=>"468","kode_penyakit"=>"E10.6"),
            array("diagnosa"=>"Fracture of unspecified body region","id"=>"469","kode_penyakit"=>"T14.2"),
            array("diagnosa"=>"Fracture of unspecified body region, closed","id"=>"470","kode_penyakit"=>"T14.20"),
            array("diagnosa"=>"Pseudofolliculitis barbae","id"=>"471","kode_penyakit"=>"L73.1"),
            array("diagnosa"=>"Common arterial trunk","id"=>"472","kode_penyakit"=>"Q20.0"),
            array("diagnosa"=>"Maternal care for breech presentation","id"=>"473","kode_penyakit"=>"O32.1"),
            array("diagnosa"=>"Threatened abortion","id"=>"474","kode_penyakit"=>"O20.0"),
            array("diagnosa"=>"Senile cataract, unspecified","id"=>"475","kode_penyakit"=>"H25.9"),
            array("diagnosa"=>"Irritant contact dermatitis","id"=>"476","kode_penyakit"=>"L24"),
            array("diagnosa"=>"Other specified abnormal uterine and vaginal bleeding","id"=>"477","kode_penyakit"=>"N93.8"),
            array("diagnosa"=>"Other diseases of jaws","id"=>"478","kode_penyakit"=>"K10"),
            array("diagnosa"=>"Epistaxis","id"=>"479","kode_penyakit"=>"R04.0"),
            array("diagnosa"=>"Malignant neoplasm of endometrium","id"=>"480","kode_penyakit"=>"C54.1"),
            array("diagnosa"=>"Malignant neoplasm of ovary","id"=>"481","kode_penyakit"=>"C56"),
            array("diagnosa"=>"Allergic contact dermatitis due to adhesives","id"=>"482","kode_penyakit"=>"L23.1"),
            array("diagnosa"=>"Other aplastic anaemias","id"=>"483","kode_penyakit"=>"D61"),
            array("diagnosa"=>"Other tetanus","id"=>"484","kode_penyakit"=>"A35"),
            array("diagnosa"=>"Myalgia, hand","id"=>"485","kode_penyakit"=>"M79.14"),
            array("diagnosa"=>"Other mixed anxiety disorders","id"=>"486","kode_penyakit"=>"F41.3"),
            array("diagnosa"=>"Chronic kidney disease, stage 3","id"=>"487","kode_penyakit"=>"N18.3"),
            array("diagnosa"=>"Chest pain, unspecified","id"=>"488","kode_penyakit"=>"R07.4"),
            array("diagnosa"=>"Hepatomegaly and splenomegaly, not elsewhere classified","id"=>"489","kode_penyakit"=>"R16"),
            array("diagnosa"=>"Sleep apnoea","id"=>"490","kode_penyakit"=>"G47.3"),
            array("diagnosa"=>"Undescended testicle, unilateral","id"=>"491","kode_penyakit"=>"Q53.1"),
            array("diagnosa"=>"Chronic kidney disease","id"=>"492","kode_penyakit"=>"N18"),
            array("diagnosa"=>"Chronic laryngitis","id"=>"493","kode_penyakit"=>"J37.0"),
            array("diagnosa"=>"Cellulitis, unspecified","id"=>"494","kode_penyakit"=>"L03.9"),
            array("diagnosa"=>"Cervical disc disorders","id"=>"495","kode_penyakit"=>"M50"),
            array("diagnosa"=>"Functional diarrhoea","id"=>"496","kode_penyakit"=>"K59.1"),
            array("diagnosa"=>"Unspecified renal colic","id"=>"497","kode_penyakit"=>"N23"),
            array("diagnosa"=>"Other post-traumatic coxarthrosis","id"=>"498","kode_penyakit"=>"M16.5"),
            array("diagnosa"=>"Anomalies of tooth position","id"=>"499","kode_penyakit"=>"K07.3"),
            array("diagnosa"=>"Heart failure, unspecified","id"=>"500","kode_penyakit"=>"I50.9"),
            array("diagnosa"=>"Other hearing loss","id"=>"501","kode_penyakit"=>"H91"),
            array("diagnosa"=>"Otitis media, unspecified","id"=>"502","kode_penyakit"=>"H66.9"),
            array("diagnosa"=>"Lumbar and other intervertebral disc disorders with radiculopathy","id"=>"503","kode_penyakit"=>"M51.1"),
            array("diagnosa"=>"Otitis externa in mycoses","id"=>"504","kode_penyakit"=>"H62.2"),
            array("diagnosa"=>"Other epidermal thickening","id"=>"505","kode_penyakit"=>"L85"),
            array("diagnosa"=>"Other atopic dermatitis","id"=>"506","kode_penyakit"=>"L20.8"),
            array("diagnosa"=>"Haemorrhage from throat","id"=>"507","kode_penyakit"=>"R04.1"),
            array("diagnosa"=>"Nonorganic hypersomnia","id"=>"508","kode_penyakit"=>"F51.1"),
            array("diagnosa"=>"Hypoaesthesia of skin","id"=>"509","kode_penyakit"=>"R20.1"),
            array("diagnosa"=>"Other anaemias","id"=>"510","kode_penyakit"=>"D64"),
            array("diagnosa"=>"Monoarthritis, not elsewhere classified, pelvic and thigh","id"=>"511","kode_penyakit"=>"M13.15"),
            array("diagnosa"=>"Other noninflammatory disorders of vagina","id"=>"512","kode_penyakit"=>"N89"),
            array("diagnosa"=>"Noninflammatory disorder of vagina, unspecified","id"=>"513","kode_penyakit"=>"N89.9"),
            array("diagnosa"=>"Non-insulin-dependent diabetes mellitus without complications","id"=>"514","kode_penyakit"=>"E11.9"),
            array("diagnosa"=>"Postzoster neuralgia","id"=>"515","kode_penyakit"=>"G53.0"),
            array("diagnosa"=>"Chronic gastritis, unspecified","id"=>"516","kode_penyakit"=>"K29.5"),
            array("diagnosa"=>"Naevus, non-neoplastic","id"=>"517","kode_penyakit"=>"I78.1"),
            array("diagnosa"=>"Complicated migraine","id"=>"518","kode_penyakit"=>"G43.3"),
            array("diagnosa"=>"Acute renal failure","id"=>"519","kode_penyakit"=>"N17"),
            array("diagnosa"=>"Sequelae of other specified burn, corrosion and frostbite","id"=>"520","kode_penyakit"=>"T95.8"),
            array("diagnosa"=>"Cerebral infarction","id"=>"521","kode_penyakit"=>"I63"),
            array("diagnosa"=>"Polyarthritis, unspecified, hand","id"=>"522","kode_penyakit"=>"M13.04"),
            array("diagnosa"=>"Disorder of tympanic membrane, unspecified","id"=>"523","kode_penyakit"=>"H73.9"),
            array("diagnosa"=>"Acute mastoiditis","id"=>"524","kode_penyakit"=>"H70.0"),
            array("diagnosa"=>"Chronic viral hepatitis","id"=>"525","kode_penyakit"=>"B18"),
            array("diagnosa"=>"Sequelae of dislocation, sprain and strain of upper limb","id"=>"526","kode_penyakit"=>"T92.3"),
            array("diagnosa"=>"Fracture of tooth, closed","id"=>"527","kode_penyakit"=>"S02.50"),
            array("diagnosa"=>"Low back pain, sacral and sacrococcygeal region","id"=>"528","kode_penyakit"=>"M54.58"),
            array("diagnosa"=>"Sleep disorders","id"=>"529","kode_penyakit"=>"G47"),
            array("diagnosa"=>"Chronic maxillary sinusitis","id"=>"530","kode_penyakit"=>"J32.0"),
            array("diagnosa"=>"Other local infections of skin and subcutaneous tissue","id"=>"531","kode_penyakit"=>"L08"),
            array("diagnosa"=>"Myalgia, pelvic and thigh","id"=>"532","kode_penyakit"=>"M79.15"),
            array("diagnosa"=>"Localized oedema","id"=>"533","kode_penyakit"=>"R60.0"),
            array("diagnosa"=>"Other erythematous conditions","id"=>"534","kode_penyakit"=>"L53"),
            array("diagnosa"=>"Other specified intervertebral disc disorders","id"=>"535","kode_penyakit"=>"M51.8"),
            array("diagnosa"=>"Bipolar affective disorder, current episode severe depression without psychotic symptoms","id"=>"536","kode_penyakit"=>"F31.4"),
            array("diagnosa"=>"Disturbances of skin sensation","id"=>"537","kode_penyakit"=>"R20"),
            array("diagnosa"=>"Abscess of anal and rectal regions","id"=>"538","kode_penyakit"=>"K61"),
            array("diagnosa"=>"Embolism and thrombosis of arteries of lower extremities","id"=>"539","kode_penyakit"=>"I74.3"),
            array("diagnosa"=>"Anorexia","id"=>"540","kode_penyakit"=>"R63.0"),
            array("diagnosa"=>"Internal haemorrhoids without complication","id"=>"541","kode_penyakit"=>"I84.2"),
            array("diagnosa"=>"Convergent concomitant strabismus","id"=>"542","kode_penyakit"=>"H50.0"),
            array("diagnosa"=>"Irritable bowel syndrome","id"=>"543","kode_penyakit"=>"K58"),
            array("diagnosa"=>"Miliary tuberculosis, unspecified","id"=>"544","kode_penyakit"=>"A19.9"),
            array("diagnosa"=>"Benign neoplasm of breast","id"=>"545","kode_penyakit"=>"D24"),
            array("diagnosa"=>"Gastroenteritis and colitis of unspecified origin","id"=>"546","kode_penyakit"=>"A09.9"),
            array("diagnosa"=>"Unspecified haematuria","id"=>"547","kode_penyakit"=>"R31"),
            array("diagnosa"=>"Allergic contact dermatitis due to other chemical products","id"=>"548","kode_penyakit"=>"L23.5"),
            array("diagnosa"=>"Tuberculosis of bones and joints","id"=>"549","kode_penyakit"=>"A18.0"),
            array("diagnosa"=>"Loss of teeth due to accident, extraction or local periodontal disease","id"=>"550","kode_penyakit"=>"K08.1"),
            array("diagnosa"=>"Other benign neoplasm of connective and other soft tissue of lower limb, including hip","id"=>"551","kode_penyakit"=>"D21.2"),
            array("diagnosa"=>"Unspecified appendicitis","id"=>"552","kode_penyakit"=>"K37"),
            array("diagnosa"=>"Essential thrombocytosis","id"=>"553","kode_penyakit"=>"D75.2"),
            array("diagnosa"=>"Noninfective gastroenteritis and colitis, unspecified","id"=>"554","kode_penyakit"=>"K52.9"),
            array("diagnosa"=>"Other noninfective gastroenteritis and colitis","id"=>"555","kode_penyakit"=>"K52"),
            array("diagnosa"=>"Haemorrhage, not elsewhere classified","id"=>"556","kode_penyakit"=>"R58"),
            array("diagnosa"=>"Other specified noninfective gastroenteritis and colitis","id"=>"557","kode_penyakit"=>"K52.8"),
            array("diagnosa"=>"Neurofibromatosis (nonmalignant)","id"=>"558","kode_penyakit"=>"Q85.0"),
            array("diagnosa"=>"","id"=>"559","kode_penyakit"=>"K02"),
            array("diagnosa"=>"Bursitis of hand","id"=>"560","kode_penyakit"=>"M70.1"),
            array("diagnosa"=>"Primary respiratory tuberculosis without mention of bacteriological or histological confirmation","id"=>"561","kode_penyakit"=>"A16.7"),
            array("diagnosa"=>"Other urethritis","id"=>"562","kode_penyakit"=>"N34.2"),
            array("diagnosa"=>"Cluster headache syndrome","id"=>"563","kode_penyakit"=>"G44.0"),
            array("diagnosa"=>"Moderate protein-energy malnutrition","id"=>"564","kode_penyakit"=>"E44.0"),
            array("diagnosa"=>"Bronchitis, not specified as acute or chronic","id"=>"565","kode_penyakit"=>"J40"),
            array("diagnosa"=>"Nummular dermatitis","id"=>"566","kode_penyakit"=>"L30.0"),
            array("diagnosa"=>"Gastro-oesophageal reflux disease without oesophagitis","id"=>"567","kode_penyakit"=>"K21.9"),
            array("diagnosa"=>"Urethral stricture","id"=>"568","kode_penyakit"=>"N35"),
            array("diagnosa"=>"Iron deficiency anaemia, unspecified","id"=>"D50.9","kode_penyakit"=>"D50.9"),
            array("diagnosa"=>"Abnormal results of kidney function studies","id"=>"570","kode_penyakit"=>"R94.4"),
            array("diagnosa"=>"Other nutritional anaemias","id"=>"571","kode_penyakit"=>"D53"),
            array("diagnosa"=>"Maternal care for disproportion, unspecified","id"=>"572","kode_penyakit"=>"O33.9"),
            array("diagnosa"=>"Unspecified haemorrhoids without complication","id"=>"573","kode_penyakit"=>"I84.9"),
            array("diagnosa"=>"Feeding difficulties and mismanagement","id"=>"574","kode_penyakit"=>"R63.3"),
            array("diagnosa"=>"Anterior spinal and vertebral artery compression syndromes","id"=>"575","kode_penyakit"=>"M47.0"),
            array("diagnosa"=>"Bullous disorder, unspecified","id"=>"576","kode_penyakit"=>"L13.9"),
            array("diagnosa"=>"Manic episode","id"=>"577","kode_penyakit"=>"F30"),
        );

        DB::table('diseases')->insert($diseases);
    }
}
